<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>inventory_app</RootNamespace>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <ContainerRuntimeIdentifier>win-x64</ContainerRuntimeIdentifier>
    <EnableSdkContainerDebugging>True</EnableSdkContainerDebugging>
    <ContainerBaseImage>mcr.microsoft.com/dotnet/aspnet:8.0-nanoserver-1809</ContainerBaseImage>
    <UserSecretsId>21710954-5372-4b4b-b79c-aa32ddfa127a</UserSecretsId>
    <DockerfileContext>.</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <ContainerPort Include="8081" />
  </ItemGroup>

</Project>
